# Generated by Django 4.1.7 on 2023-04-01 16:21

from django.db import migrations
import os
from django.db.utils import IntegrityError
import logging

logger = logging.getLogger("django")


def generate_superuser(apps, schema_editor):
    """Create a new superuser """
    from django.contrib.auth import get_user_model

    username = os.environ.get("SUPER_ADMIN_EMAIL_ADDRESS", default='admin')
    password = os.environ.get("SUPER_ADMIN_PASSWORD", default='admin')

    try:
        superuser, created = get_user_model().objects.get_or_create(
            username=username)
        if created:
            superuser.set_password(password)
            superuser.is_superuser = True
            superuser.is_staff = True
            superuser.save()
    except IntegrityError as e:
        logger.error(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]
