# Generated by Django 4.1.7 on 2023-04-01 23:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changed_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporal_pin',
            field=models.CharField(blank=True, default=accounts.models.User.get_pin, max_length=10, null=True),
        ),
    ]
