# Generated by Django 4.1.7 on 2023-04-01 23:01

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_changed_password_alter_user_temporal_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temporal_pin',
            field=models.CharField(default=accounts.models.User.get_pin, max_length=10),
        ),
    ]
