# Generated by Django 3.2.11 on 2022-06-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('remark', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'grading_systems',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('form', models.IntegerField(default=1)),
                ('stream', models.CharField(max_length=5)),
                ('class_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klass', to='staff.staff')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.course')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_elective', models.BooleanField()),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TeacherClassSubjectCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='students.klass', verbose_name='Class')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='staff.staff', verbose_name='Staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='students.subject')),
            ],
            options={
                'db_table': 'teacher_class_subject_combination',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('sms_number', models.CharField(max_length=10)),
                ('temporal_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('house', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('track', models.CharField(max_length=50)),
                ('father', models.CharField(blank=True, max_length=200, null=True)),
                ('mother', models.CharField(blank=True, max_length=200, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('last_promotion_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.FileField(default='/images/avatar.jpg', upload_to='media/images/students')),
                ('electives', models.ManyToManyField(blank=True, related_name='students', to='students.Subject')),
                ('klass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.klass')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_score', models.IntegerField(blank=True, default=0, null=True)),
                ('class_score', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=5, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('klass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.klass')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='staff.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.subject')),
            ],
            options={
                'db_table': 'academic_records',
            },
        ),
        migrations.CreateModel(
            name='HouseMasterRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.klass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'house_master_remarks',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='students.Subject'),
        ),
        migrations.CreateModel(
            name='ClassTeacherRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=50)),
                ('attendance', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('attitude', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('conduct', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.klass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'class_teacher_remarks',
            },
        ),
    ]
