from .classes import *
from .courses import *
from .departments import *
from .houses import *
from .main import *
from .staff import *
from .students import *
from .subjects import *
from .action_center import *
from .reporting import *
from .class_teacher_report import *
