# Generated by Django 3.2.11 on 2022-06-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('sms_number', models.CharField(max_length=10)),
                ('has_left', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=10)),
                ('has_class', models.BooleanField(default=True)),
                ('temporal_pin', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated', models.BooleanField(default=False)),
                ('image', models.FileField(default='/images/avatar.jpg', upload_to='uploads/images/staff')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='HouseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=50)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housemaster', to='staff.staff')),
            ],
        ),
    ]
