# Generated by Django 3.2.11 on 2022-07-10 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20220710_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradingsystem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
