# Generated by Django 3.2.11 on 2022-07-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20220710_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attitude',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='text',
            new_name='name',
        ),
    ]
