# Generated by Django 3.2.11 on 2022-07-10 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('setup', '0004_auto_20220710_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingsystem',
            options={'ordering': ['-min_score']},
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='min_score',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos')),
                ('sms_sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_active', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assistant_head_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_school', to='dashboard.staff')),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.schoolsession')),
                ('head_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.staff')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
