# Generated by Django 3.2.11 on 2022-07-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('setup', '0005_auto_20220710_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='assistant_head_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_school', to='dashboard.staff'),
        ),
        migrations.AlterField(
            model_name='school',
            name='head_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.staff'),
        ),
    ]
