# Generated by Django 3.2.11 on 2022-07-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20220710_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='current_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.track'),
        ),
    ]
