# Generated by Django 3.2.11 on 2022-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_schoolsession_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsession',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='schoolsession',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
