# Generated by Django 4.1.7 on 2023-04-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_attitude_id_alter_conduct_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupperms',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_setup', 'Can manage system setup'), ('view_dashboard', 'Can view application dashboard'), ('manage_notifications', 'Can view and send notifications.')]},
        ),
    ]
