# Generated by Django 4.1.7 on 2023-04-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_setupperms_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupperms',
            options={'default_permissions': (), 'managed': False, 'permissions': [('manage_setup', 'Can manage system setup'), ('view_dashboard', 'Can view application dashboard'), ('manage_notifications', 'Can view and send notifications.'), ('manage_accounting', 'Can access accounting menu')]},
        ),
    ]
