# Generated by Django 4.1.7 on 2023-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_alter_setupperms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sms_balance',
            field=models.IntegerField(default=0),
        ),
    ]
