# Generated by Django 4.1.7 on 2023-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_alter_setupperms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsession',
            name='next_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Date'),
        ),
    ]
