# Generated by Django 3.2.11 on 2022-07-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_subject_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.house'),
        ),
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='dashboard.klass'),
        ),
    ]
