# Generated by Django 3.2.11 on 2022-07-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_schoolsession_tracks'),
        ('dashboard', '0005_auto_20220711_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='dashboard.klass', verbose_name='Class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.schoolsession')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='dashboard.staff', verbose_name='Staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='dashboard.subject')),
            ],
            options={
                'db_table': 'subject_mapping',
            },
        ),
        migrations.DeleteModel(
            name='SubjectAssignment',
        ),
    ]
