# Generated by Django 3.2.11 on 2022-07-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220712_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmapping',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='dashboard.staff', verbose_name='Staff'),
            preserve_default=False,
        ),
    ]
