# Generated by Django 3.2.11 on 2022-07-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_subjectmapping_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='dashboard.staff'),
        ),
        migrations.DeleteModel(
            name='PromotionHistory',
        ),
    ]
