# Generated by Django 3.2.11 on 2022-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20220713_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('manage_other_record', 'Can add/change academic/classwork records of other teachers')]},
        ),
        migrations.RemoveField(
            model_name='record',
            name='klass',
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
