# Generated by Django 3.2.11 on 2022-07-14 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20220713_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='dashboard.staff'),
        ),
    ]
