# Generated by Django 3.2.11 on 2022-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_record_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='total_class_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='total_exam_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
