# Generated by Django 3.2.11 on 2022-07-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20220714_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='uploaded_by',
            new_name='updated_by',
        ),
    ]
