# Generated by Django 3.2.11 on 2022-07-14 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0014_rename_uploaded_by_record_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
    ]
