# Generated by Django 3.2.11 on 2022-07-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_record_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.klass'),
        ),
    ]
