# Generated by Django 3.2.11 on 2022-07-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_studentpromotionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpromotionhistory',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.klass'),
        ),
    ]
