# Generated by Django 3.2.11 on 2022-07-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_studentpromotionhistory_klass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpromotionhistory',
            old_name='klass',
            new_name='new_class',
        ),
    ]
