# Generated by Django 3.2.11 on 2022-07-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_klass_studentpromotionhistory_new_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpromotionhistory',
            name='old_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_classes', to='dashboard.klass'),
        ),
        migrations.AlterField(
            model_name='studentpromotionhistory',
            name='new_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_classes', to='dashboard.klass'),
        ),
    ]
