# Generated by Django 3.2.11 on 2022-07-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20220718_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classteacherreport',
            old_name='remark',
            new_name='class_teacher_remark',
        ),
        migrations.AddField(
            model_name='classteacherreport',
            name='house_master_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='HouseMasterRemark',
        ),
    ]
