# Generated by Django 3.2.11 on 2022-07-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_remark'),
        ('dashboard', '0022_auto_20220719_0319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTeacherReport',
            new_name='SessionReport',
        ),
    ]
