# Generated by Django 3.2.11 on 2022-07-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_rename_classteacherreport_sessionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreport',
            name='promotion',
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
