# Generated by Django 3.2.11 on 2022-07-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20220719_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreport',
            name='promoted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
