# Generated by Django 3.2.11 on 2022-07-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_sessionreport_promoted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionreport',
            options={'permissions': [('manage_other_report', 'Can manage reports of other classes.')]},
        ),
    ]
