# Generated by Django 3.2.11 on 2022-07-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_remark'),
        ('dashboard', '0026_alter_sessionreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreport',
            name='class_teacher_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.remark'),
        ),
    ]
