# Generated by Django 3.2.11 on 2022-07-19 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_remark'),
        ('dashboard', '0027_alter_sessionreport_class_teacher_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreport',
            name='promoted',
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='promotion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='attitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.attitude'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='class_teacher_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.remark'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='conduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.conduct'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='house_master_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='house_master_remark', to='setup.remark'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.interest'),
        ),
    ]
