# Generated by Django 3.2.11 on 2022-07-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_sessionreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionreport',
            options={'permissions': [('manage_other_report', 'Can manage reports of other classes.'), ('manage_class_teacher_report', 'Can manage class teacher report.'), ('manage_house_master_report', 'Can manage house master report.'), ('append_assistance_head_signature', 'Can append assistance head signature.')]},
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='assistant_head_signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/signatures'),
        ),
    ]
