# Generated by Django 3.2.11 on 2022-07-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_studentpromotionhistory_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.staff'),
        ),
    ]
