# Generated by Django 4.1.7 on 2023-04-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0003_remove_invoice_student_invoice_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='description',
            new_name='name',
        ),
    ]
