# Generated by Django 4.1.7 on 2023-04-09 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import graphql_api.models.accounting


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_account'),
        ('graphql_api', '0005_invoiceitem_created_by_invoiceitem_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'APPLIED'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING')], max_length=100),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=graphql_api.models.accounting.Transaction.generate_id, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='new', max_length=255, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_balances_updated', models.BooleanField(default=False)),
                ('accepted_by_provider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
