# Generated by Django 4.1.7 on 2023-04-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0007_invoice_session_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet_balances_updated',
            new_name='account_balances_updated',
        ),
    ]
