# Generated by Django 4.1.7 on 2023-09-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_systemnotification'),
        ('graphql_api', '0009_invoiceitem_deleted_transaction_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
    ]
