from .accounting import *
from .action_center import *
from .assistant_head_report import *
from .class_teacher_report import *
from .classes import *
from .courses import *
from .departments import *
from .house_master_report import *
from .houses import *
from .main import *
from .notifications import *
from .reporting import *
from .staff import *
from .students import *
from .subjects import *
from .inventory import *
from .personal import *
from .tasks import *
