# Generated by Django 4.1.7 on 2023-04-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_relative_username_relative_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='klass',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='relative',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentpromotionhistory',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False, unique=True),
        ),
    ]
