# Generated by Django 4.1.7 on 2023-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_hometown_student_home_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='spouses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
