# Generated by Django 4.1.7 on 2023-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_notification_sender_id_alter_student_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='group_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
