# Generated by Django 4.1.7 on 2023-04-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_record_group_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
