# Generated by Django 4.1.7 on 2023-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_record_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rank',
        ),
        migrations.AddField(
            model_name='student',
            name='sms_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='group_tag',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
