# Generated by Django 4.1.7 on 2023-05-04 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0017_school_sms_balance'),
        ('dashboard', '0016_notification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='dashboard.course'),
        ),
        migrations.AlterField(
            model_name='record',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.schoolsession'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.klass'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='dashboard.department'),
        ),
    ]
