# Generated by Django 4.1.7 on 2023-05-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_inventory_issuance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='noted',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='issuance',
            old_name='noted',
            new_name='note',
        ),
    ]
