# Generated by Django 4.1.7 on 2023-05-04 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_alter_inventory_id_alter_issuance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='status',
            field=models.CharField(choices=[('returned', 'returned'), ('pending', 'pending'), ('overdue', 'overdue')], default='pending', max_length=50),
        ),
    ]
