# Generated by Django 4.1.7 on 2023-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_issuance_updated_by_alter_issuance_issued_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
