# Generated by Django 4.1.7 on 2023-05-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_alter_setupperms_options'),
        ('dashboard', '0022_alter_issuance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpromotionhistory',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.schoolsession'),
        ),
    ]
