# Generated by Django 4.1.7 on 2023-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_course_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='courses', to='dashboard.department'),
        ),
    ]
