# Generated by Django 4.1.7 on 2023-06-22 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_alter_setupperms_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0027_alter_course_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuance',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('task_type', models.CharField(choices=[('academic_record', 'academic_record'), ('class_teacher_report', 'class_teacher_report'), ('assitant_head_signature', 'assitant_head_signature'), ('houe_master_report', 'houe_master_report')], max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_process', 'in_process'), ('completed', 'completed'), ('overdue', 'overdue')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redirect_link', models.URLField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.schoolsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
