# Generated by Django 4.1.7 on 2023-06-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_issuance_expiry_date_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='class_score',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='exam_score',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='total',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_process', 'in_process'), ('completed', 'completed'), ('warning', 'warning'), ('overdue', 'overdue')], max_length=20),
        ),
    ]
