# Generated by Django 4.1.7 on 2023-06-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_record_class_score_alter_record_exam_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='class_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='exam_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
