# Generated by Django 4.1.7 on 2023-06-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_record_class_score_alter_record_exam_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('academic_record', 'academic_record'), ('class_teacher_report', 'class_teacher_report'), ('assitant_head_signature', 'assitant_head_signature'), ('houe_master_report', 'houe_master_report'), ('other', 'other')], max_length=50),
        ),
    ]
