# Generated by Django 4.1.7 on 2023-06-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_task_notified_at_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
