# Generated by Django 4.1.7 on 2023-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_task_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='noted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
