# Generated by Django 4.1.7 on 2023-12-22 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0024_alter_setupperms_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0034_systemnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inventory'),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='klass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='dashboard.course'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.schoolsession'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='attitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.attitude'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='class_teacher_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.remark'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='conduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.conduct'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='house_master_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_master_remark', to='setup.remark'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.interest'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.klass'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.staff'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='dashboard.department'),
        ),
    ]
